tag @a remove j
tag @a remove m
tag @a remove k
tag @a remove t
tag @a remove d
tag @a remove jt
tag @a remove mt
tag @a remove c
tag @a remove mk
tag @a remove jk
tag @a remove tk
tag @a remove dk
tag @a remove kk
tag @a remove ck
tag @a remove betp
tag @a remove aftp